ALTER TABLE accounts ADD COLUMN current_depth INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN current_stamina INTEGER NOT NULL DEFAULT 100;
ALTER TABLE accounts ADD COLUMN deepest_depth INTEGER NOT NULL DEFAULT 0;